Core concepts
ryanharmanepam/netflix-clone pull request #1
Opened 2022-06-06 08:17 UTC by ryanharmanepam

2022-06-09 11:05 UTC, eduardo-neto-epam requested changes
Remember that if you're using React 18, to use its features.
Make sure to do your best to provide a clean and optimised code.
Congratulations on using Typescript, that said, make sure elements are properly typed.

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/counter/index.tsx
> +      <Button onClick={() => setCurrentCount(currentCount - 1)}>Down!</Button>
Avoid the use of in-line functions.

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/genreSelection/index.tsx
> +];
Try to place mockData in its own file.

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/genreSelection/index.tsx
> +    const newTabs = tabs.map((i) =>
Avoid the use of single characters. Try to be descriptive with your variables. "i " can be easily confused with index. if you call the variable tab, readability improves.

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/genreSelection/index.tsx
> +import React, { useState } from "react";
Avoid to declare variables that are not used. e.g. React
React 18 does not need the import React

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/ui/tabs/index.tsx
> +        <div onClick={() => onTabClick(i.id)}>{i.name}</div>
I suggest the creation of a Tab component as a UI element. Tabs is more of a container/layout.
Make sure when using map to add a key prop to the children.
Also, consider something like this to see what tab is active:
`      {tabs.map(({id, name, isSelected}) => (
        <div key={id} onClick={() => onTabClick(id)}>{name} - {isSelected && 'ACTIVE'}</div>
      ))}`

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/ui/button/index.tsx
> +interface ButtonProps {
A button component should have the same props as a native html button.
ref: https://dev.indooroutdoor.io/how-to-extend-any-html-element-with-react-and-typescript
https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/#wrappingmirroring-a-html-element

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/ui/input/index.tsx
> +
See https://dev.to/giselamd/creating-a-react-input-component-in-typescript-hai for a generic Input well typed.

2022-06-09 11:05 UTC, eduardo-neto-epam commented on src/components/ui/input/index.tsx
> +import React from "react";
No need for this in React 18

2022-06-10 09:29 UTC, ryanharmanepam commented on src/components/ui/tabs/index.tsx
> +        <div onClick={() => onTabClick(i.id)}>{i.name}</div>
Tab component has been created

2022-06-16 09:44 UTC, eduardo-neto-epam approved these changes
Well done,  although onSearch got away from being fixed.

2022-06-16 09:44 UTC, eduardo-neto-epam commented on src/components/searchForm/index.tsx
> +      <Button onClick={() => onSearch()}>Search</Button>
No need to pass a callback to call onSearch if you have no arguments to pass to the function.

2022-06-16 10:21 UTC, merged